
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author byron
 */
public class jExamen extends javax.swing.JFrame {

       
    public jExamen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitulo = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        jFechaDeNacimiento = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jDia = new javax.swing.JLabel();
        jMes = new javax.swing.JLabel();
        jAno = new javax.swing.JLabel();
        jTextDia = new javax.swing.JTextField();
        jTextMes = new javax.swing.JTextField();
        jTextAno = new javax.swing.JTextField();
        jMonto = new javax.swing.JLabel();
        jPorcentaje = new javax.swing.JLabel();
        jDescuento = new javax.swing.JLabel();
        jTextMonto = new javax.swing.JTextField();
        jTextPorcentaje = new javax.swing.JTextField();
        jTextDescuento = new javax.swing.JTextField();
        jTextTotal = new javax.swing.JTextField();
        jTotal = new javax.swing.JLabel();
        jBtnValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTitulo.setText("COMPU ASERRÍ");

        jNombre.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jNombre.setText("NOMBRE:");

        jFechaDeNacimiento.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jFechaDeNacimiento.setText("Fecha de nacimiento:");

        jTextNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jDia.setText("día");

        jMes.setText("mes");

        jAno.setText("año:");

        jMonto.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jMonto.setText("MONTO:");

        jPorcentaje.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jPorcentaje.setText("Porcentaje de descuento:");

        jDescuento.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jDescuento.setText("Descuento:");

        jTotal.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jTotal.setText("TOTAL:");

        jBtnValidar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnValidar.setText("VALIDAR");
        jBtnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFechaDeNacimiento)
                                .addGap(22, 22, 22)
                                .addComponent(jDia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextDia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jMes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextMes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jAno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextAno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTitulo)))
                        .addGap(253, 253, 253))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNombre)
                        .addGap(26, 26, 26)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jMonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jPorcentaje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDescuento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jBtnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTitulo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNombre))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFechaDeNacimiento)
                    .addComponent(jDia)
                    .addComponent(jAno)
                    .addComponent(jMes)
                    .addComponent(jTextMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMonto)
                    .addComponent(jPorcentaje)
                    .addComponent(jDescuento)
                    .addComponent(jTextMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal)
                    .addComponent(jBtnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnValidarActionPerformed
     int ano,anoactual,edad,monto;  
     String nombre;
     double descuento,junior,executive,senior,total;
     descuento = 0.0;
     junior = 0.10;
     executive = 0.15;
     senior = 0.20;     
     nombre = jTextNombre.getText();
     anoactual = 2022;
     ano =Integer.parseInt(jTextAno.getText());
     edad = anoactual - ano;
     monto =Integer.parseInt(jTextMonto.getText());
     if (edad > 15 && edad < 25){
         
         descuento= monto * junior;
         total = monto - descuento;         
         JOptionPane.showMessageDialog(null,"Bienvenido "+ nombre +"\nUsted tiene un porcentaje de descuento de: 10%"+"\nEl descuento es de: "+descuento+"\nEl monto a pagar es de: "+ total);
     }
      if (edad > 25 && edad < 35){
         
         descuento= monto * executive;
         total = monto - descuento;         
         JOptionPane.showMessageDialog(null,"Bienvenido "+ nombre +"\nUsted tiene un porcentaje de descuento de: 15%"+"\nEl descuento es de: "+descuento+"\nEl monto a pagar es de: "+ total);     }
       if (edad > 35){
         
         descuento= monto * senior;
         total = monto - descuento;         
         JOptionPane.showMessageDialog(null,"Bienvenido "+ nombre +"\nUsted tiene un porcentaje de descuento de: 20%"+"\nEl descuento es de: "+descuento+"\nEl monto a pagar es de: "+ total);
     }
    }//GEN-LAST:event_jBtnValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jExamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAno;
    private javax.swing.JButton jBtnValidar;
    private javax.swing.JLabel jDescuento;
    private javax.swing.JLabel jDia;
    private javax.swing.JLabel jFechaDeNacimiento;
    private javax.swing.JLabel jMes;
    private javax.swing.JLabel jMonto;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jPorcentaje;
    private javax.swing.JTextField jTextAno;
    private javax.swing.JTextField jTextDescuento;
    private javax.swing.JTextField jTextDia;
    private javax.swing.JTextField jTextMes;
    private javax.swing.JTextField jTextMonto;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPorcentaje;
    private javax.swing.JTextField jTextTotal;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JLabel jTotal;
    // End of variables declaration//GEN-END:variables
}
